# display time in seconds (min 1s)
display-time: 3

# Change nickname format here
# Use & for colors or HEX (#RRGGBB) and {PLAYER_NAME} variable
name-format: "&a{PLAYER_NAME}"

# If true, plugin will NOT show nametag when the target player is invisible
respect-invisibility: false

# Where to display the nickname: "actionbar" (default) or "subtitle"
display-location: "actionbar"

# Translations
Messages:
  Reload: "&aRMBNametags config reloaded!"
  Not-Reload: "&cAn error occurred during a config reload"
